spring:
  application:
    name: cloud-eureka-admin

server:
  port: 8084

eureka:
  instance:
    hostname: 101.132.67.220
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/