spring:
  application:
    name: cloud-eureka-feign
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8765


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

feign:
  hystrix:
    enabled: true