spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  instance:
    hostname: 101.132.67.220
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/