spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: cloud-zuul-gateway
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

zuul:
  routes:
    api-business-admin:
      # 以 /api/business/admin 开头的请求都转发给 business-admin 服务
      path: /api/business/admin/**
      serviceId: business-admin